// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/broker/book-of-business/[groupId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker/book-of-business/[groupId]">> = Specific
  const handler = {} as typeof import("../../app/broker/book-of-business/[groupId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broker/book-of-business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker/book-of-business">> = Specific
  const handler = {} as typeof import("../../app/broker/book-of-business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broker/commissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker/commissions">> = Specific
  const handler = {} as typeof import("../../app/broker/commissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broker/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker/documents">> = Specific
  const handler = {} as typeof import("../../app/broker/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broker/enrollments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker/enrollments">> = Specific
  const handler = {} as typeof import("../../app/broker/enrollments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker">> = Specific
  const handler = {} as typeof import("../../app/broker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broker/quotes/[quoteId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker/quotes/[quoteId]">> = Specific
  const handler = {} as typeof import("../../app/broker/quotes/[quoteId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broker/quotes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker/quotes/new">> = Specific
  const handler = {} as typeof import("../../app/broker/quotes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broker/quotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker/quotes">> = Specific
  const handler = {} as typeof import("../../app/broker/quotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broker/renewals/[renewalId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker/renewals/[renewalId]">> = Specific
  const handler = {} as typeof import("../../app/broker/renewals/[renewalId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broker/renewals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker/renewals">> = Specific
  const handler = {} as typeof import("../../app/broker/renewals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broker/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker/support">> = Specific
  const handler = {} as typeof import("../../app/broker/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/broker/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/broker/tasks">> = Specific
  const handler = {} as typeof import("../../app/broker/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/authorizations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/authorizations">> = Specific
  const handler = {} as typeof import("../../app/dashboard/authorizations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/benefits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/benefits">> = Specific
  const handler = {} as typeof import("../../app/dashboard/benefits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/administration/billing-preferences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/administration/billing-preferences">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/administration/billing-preferences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/administration/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/administration/integrations">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/administration/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/administration/notification-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/administration/notification-settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/administration/notification-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/administration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/administration">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/administration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/administration/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/administration/profile">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/administration/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/administration/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/administration/users">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/administration/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/billing-invoices/[invoiceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/billing-invoices/[invoiceId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/billing-invoices/[invoiceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/billing-invoices/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/billing-invoices/history">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/billing-invoices/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/billing-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/billing-overview">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/billing-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/billing-payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/billing-payments">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/billing-payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/census-import/errors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/census-import/errors">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/census-import/errors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/census-import/history/[importId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/census-import/history/[importId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/census-import/history/[importId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/census-import/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/census-import/history">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/census-import/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/census-import/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/census-import/integrations">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/census-import/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/census-import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/census-import">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/census-import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/document-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/document-center">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/document-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/document-center/view/[documentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/document-center/view/[documentId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/document-center/view/[documentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/documents">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/documents/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/documents/upload">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/documents/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/employees/[employeeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/employees/[employeeId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/employees/[employeeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/employees">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/enrollment-activity/[requestId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/enrollment-activity/[requestId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/enrollment-activity/[requestId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/enrollment-activity/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/enrollment-activity/history">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/enrollment-activity/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/enrollment-activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/enrollment-activity">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/enrollment-activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/enrollment/household/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/enrollment/household">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/enrollment/household/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/enrollment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/enrollment">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/enrollment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/enrollment/start/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/enrollment/start">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/enrollment/start/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/enrollment/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/enrollment/status">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/enrollment/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/invoices">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/notices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/notices">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/notices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/notifications">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/notifications/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/notifications/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/notifications/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/open-enrollment/[recordId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/open-enrollment/[recordId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/open-enrollment/[recordId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/open-enrollment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/open-enrollment">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/open-enrollment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/payments/autopay/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/payments/autopay">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/payments/autopay/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/payments/current-balance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/payments/current-balance">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/payments/current-balance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/payments/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/payments/history">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/payments/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/payments/invoice/[invoiceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/payments/invoice/[invoiceId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/payments/invoice/[invoiceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/payments/make/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/payments/make">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/payments/make/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/payments/methods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/payments/methods">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/payments/methods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/payments/next-invoice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/payments/next-invoice">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/payments/next-invoice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/payments">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/payments/statements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/payments/statements">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/payments/statements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/plans/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/plans/compare">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/plans/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/plans">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/renewals/life-event/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/renewals/life-event">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/renewals/life-event/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/renewals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/renewals">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/renewals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/reports/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/reports/analytics">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/reports/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/reports">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/reports/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/reports/schedule">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/reports/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/rules">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/rules/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/rules/verify">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/rules/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/support">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/tasks/[taskId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/tasks/[taskId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/tasks/[taskId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing-enrollment/tasks">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/broker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/broker">> = Specific
  const handler = {} as typeof import("../../app/dashboard/broker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/care-cost-estimator/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/care-cost-estimator/admin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/care-cost-estimator/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/care-cost-estimator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/care-cost-estimator">> = Specific
  const handler = {} as typeof import("../../app/dashboard/care-cost-estimator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/claims/[claimId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/claims/[claimId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/claims/[claimId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/claims/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/claims">> = Specific
  const handler = {} as typeof import("../../app/dashboard/claims/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/design-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/design-preview">> = Specific
  const handler = {} as typeof import("../../app/dashboard/design-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/documents">> = Specific
  const handler = {} as typeof import("../../app/dashboard/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/enrollment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/enrollment">> = Specific
  const handler = {} as typeof import("../../app/dashboard/enrollment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/help">> = Specific
  const handler = {} as typeof import("../../app/dashboard/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/id-card/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/id-card">> = Specific
  const handler = {} as typeof import("../../app/dashboard/id-card/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/member/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/member">> = Specific
  const handler = {} as typeof import("../../app/dashboard/member/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/messages">> = Specific
  const handler = {} as typeof import("../../app/dashboard/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/provider/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider">> = Specific
  const handler = {} as typeof import("../../app/dashboard/provider/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/providers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/providers">> = Specific
  const handler = {} as typeof import("../../app/dashboard/providers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/search">> = Specific
  const handler = {} as typeof import("../../app/dashboard/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer-login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer-login">> = Specific
  const handler = {} as typeof import("../../app/employer-login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/admin">> = Specific
  const handler = {} as typeof import("../../app/employer/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/billing">> = Specific
  const handler = {} as typeof import("../../app/employer/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/documents">> = Specific
  const handler = {} as typeof import("../../app/employer/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/documents/view/[documentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/documents/view/[documentId]">> = Specific
  const handler = {} as typeof import("../../app/employer/documents/view/[documentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/eligibility-changes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/eligibility-changes">> = Specific
  const handler = {} as typeof import("../../app/employer/eligibility-changes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/employees/[employeeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/employees/[employeeId]">> = Specific
  const handler = {} as typeof import("../../app/employer/employees/[employeeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/employees">> = Specific
  const handler = {} as typeof import("../../app/employer/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/enrollment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/enrollment">> = Specific
  const handler = {} as typeof import("../../app/employer/enrollment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer">> = Specific
  const handler = {} as typeof import("../../app/employer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/reports/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/reports/analytics">> = Specific
  const handler = {} as typeof import("../../app/employer/reports/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/reports">> = Specific
  const handler = {} as typeof import("../../app/employer/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/reports/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/reports/schedule">> = Specific
  const handler = {} as typeof import("../../app/employer/reports/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer/support">> = Specific
  const handler = {} as typeof import("../../app/employer/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/billing-payments/autopay/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/billing-payments/autopay">> = Specific
  const handler = {} as typeof import("../../app/individual/billing-payments/autopay/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/billing-payments/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/billing-payments/history">> = Specific
  const handler = {} as typeof import("../../app/individual/billing-payments/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/billing-payments/invoice/[invoiceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/billing-payments/invoice/[invoiceId]">> = Specific
  const handler = {} as typeof import("../../app/individual/billing-payments/invoice/[invoiceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/billing-payments/make/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/billing-payments/make">> = Specific
  const handler = {} as typeof import("../../app/individual/billing-payments/make/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/billing-payments/methods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/billing-payments/methods">> = Specific
  const handler = {} as typeof import("../../app/individual/billing-payments/methods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/billing-payments/next-invoice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/billing-payments/next-invoice">> = Specific
  const handler = {} as typeof import("../../app/individual/billing-payments/next-invoice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/billing-payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/billing-payments">> = Specific
  const handler = {} as typeof import("../../app/individual/billing-payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/billing-payments/statements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/billing-payments/statements">> = Specific
  const handler = {} as typeof import("../../app/individual/billing-payments/statements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/documents">> = Specific
  const handler = {} as typeof import("../../app/individual/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/documents/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/documents/upload">> = Specific
  const handler = {} as typeof import("../../app/individual/documents/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/household/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/household">> = Specific
  const handler = {} as typeof import("../../app/individual/household/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/my-application/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/my-application">> = Specific
  const handler = {} as typeof import("../../app/individual/my-application/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/my-coverage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/my-coverage">> = Specific
  const handler = {} as typeof import("../../app/individual/my-coverage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual">> = Specific
  const handler = {} as typeof import("../../app/individual/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/profile">> = Specific
  const handler = {} as typeof import("../../app/individual/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/shop-plans/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/shop-plans/compare">> = Specific
  const handler = {} as typeof import("../../app/individual/shop-plans/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/shop-plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/shop-plans">> = Specific
  const handler = {} as typeof import("../../app/individual/shop-plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/individual/support">> = Specific
  const handler = {} as typeof import("../../app/individual/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/member/claims/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/claims">> = Specific
  const handler = {} as typeof import("../../app/member/claims/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/member/coverage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/coverage">> = Specific
  const handler = {} as typeof import("../../app/member/coverage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/member/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/documents">> = Specific
  const handler = {} as typeof import("../../app/member/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/member/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member">> = Specific
  const handler = {} as typeof import("../../app/member/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/member/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/profile">> = Specific
  const handler = {} as typeof import("../../app/member/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/member/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/search">> = Specific
  const handler = {} as typeof import("../../app/member/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/preview/[sessionId]/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview/[sessionId]/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/preview/[sessionId]/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/preview/error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview/error">> = Specific
  const handler = {} as typeof import("../../app/preview/error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider-login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider-login">> = Specific
  const handler = {} as typeof import("../../app/provider-login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider/admin">> = Specific
  const handler = {} as typeof import("../../app/provider/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider/authorizations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider/authorizations">> = Specific
  const handler = {} as typeof import("../../app/provider/authorizations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider/claims/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider/claims">> = Specific
  const handler = {} as typeof import("../../app/provider/claims/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider/dashboard">> = Specific
  const handler = {} as typeof import("../../app/provider/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider/documents">> = Specific
  const handler = {} as typeof import("../../app/provider/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider/eligibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider/eligibility">> = Specific
  const handler = {} as typeof import("../../app/provider/eligibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider/messages">> = Specific
  const handler = {} as typeof import("../../app/provider/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider">> = Specific
  const handler = {} as typeof import("../../app/provider/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider/patients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider/patients">> = Specific
  const handler = {} as typeof import("../../app/provider/patients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider/payments">> = Specific
  const handler = {} as typeof import("../../app/provider/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider/support">> = Specific
  const handler = {} as typeof import("../../app/provider/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin-preview/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin-preview/events">> = Specific
  const handler = {} as typeof import("../../app/api/admin-preview/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin-preview/start/[artifact]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin-preview/start/[artifact]">> = Specific
  const handler = {} as typeof import("../../app/api/admin-preview/start/[artifact]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin-preview/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin-preview/start">> = Specific
  const handler = {} as typeof import("../../app/api/admin-preview/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin-preview/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin-preview/state">> = Specific
  const handler = {} as typeof import("../../app/api/admin-preview/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/handoff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/handoff">> = Specific
  const handler = {} as typeof import("../../app/api/auth/handoff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/employer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login/employer">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/employer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/provider/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login/provider">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/provider/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/billing/autopay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/billing/autopay">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/billing/autopay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/billing/invoices/[invoiceId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/billing/invoices/[invoiceId]">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/billing/invoices/[invoiceId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/billing/payments/make/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/billing/payments/make">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/billing/payments/make/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/billing/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/billing/summary">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/billing/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/dependents/[dependentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/dependents/[dependentId]">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/dependents/[dependentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/dependents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/dependents">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/dependents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/documents">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/documents/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/documents/upload">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/documents/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/employer-dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/employer-dashboard">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/employer-dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/module-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/module-config">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/module-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/notices/[noticeId]/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/notices/[noticeId]/read">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/notices/[noticeId]/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/notices/[noticeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/notices/[noticeId]">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/notices/[noticeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/notices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/notices">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/notices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/open-enrollment/reminders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/open-enrollment/reminders">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/open-enrollment/reminders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/overview">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing-enrollment/support/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing-enrollment/support">> = Specific
  const handler = {} as typeof import("../../app/api/billing-enrollment/support/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/care-cost-estimator/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/care-cost-estimator/bootstrap">> = Specific
  const handler = {} as typeof import("../../app/api/care-cost-estimator/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/care-cost-estimator/estimate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/care-cost-estimator/estimate">> = Specific
  const handler = {} as typeof import("../../app/api/care-cost-estimator/estimate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/care-cost-estimator/saved/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/care-cost-estimator/saved">> = Specific
  const handler = {} as typeof import("../../app/api/care-cost-estimator/saved/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/employer-dashboard/workspaces/[workspace]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employer-dashboard/workspaces/[workspace]">> = Specific
  const handler = {} as typeof import("../../app/api/employer-dashboard/workspaces/[workspace]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/member-dashboard/workspaces/[workspace]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-dashboard/workspaces/[workspace]">> = Specific
  const handler = {} as typeof import("../../app/api/member-dashboard/workspaces/[workspace]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/billing-export/csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/dashboard/billing-enrollment/billing-export/csv">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/billing-export/csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/billing-export/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/dashboard/billing-enrollment/billing-export/pdf">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/billing-export/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/billing-invoices/[invoiceId]/download/csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/dashboard/billing-enrollment/billing-invoices/[invoiceId]/download/csv">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/billing-invoices/[invoiceId]/download/csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/billing-invoices/[invoiceId]/download/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/dashboard/billing-enrollment/billing-invoices/[invoiceId]/download/pdf">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/billing-invoices/[invoiceId]/download/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/document-center/download/[documentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/dashboard/billing-enrollment/document-center/download/[documentId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/document-center/download/[documentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/document-center/download/category/[category]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/dashboard/billing-enrollment/document-center/download/category/[category]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/document-center/download/category/[category]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/employees/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/dashboard/billing-enrollment/employees/export">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/employees/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/open-enrollment/report/csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/dashboard/billing-enrollment/open-enrollment/report/csv">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/open-enrollment/report/csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing-enrollment/reports/export/[reportId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/dashboard/billing-enrollment/reports/export/[reportId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing-enrollment/reports/export/[reportId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/documents/download/[documentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/employer/documents/download/[documentId]">> = Specific
  const handler = {} as typeof import("../../app/employer/documents/download/[documentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/reports/export/[reportId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/employer/reports/export/[reportId]">> = Specific
  const handler = {} as typeof import("../../app/employer/reports/export/[reportId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/health">> = Specific
  const handler = {} as typeof import("../../app/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/liveness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/liveness">> = Specific
  const handler = {} as typeof import("../../app/liveness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/readiness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/readiness">> = Specific
  const handler = {} as typeof import("../../app/readiness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/broker/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/broker">> = Specific
  const handler = {} as typeof import("../../app/broker/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/employer">> = Specific
  const handler = {} as typeof import("../../app/employer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/individual/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/individual">> = Specific
  const handler = {} as typeof import("../../app/individual/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/member/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/member">> = Specific
  const handler = {} as typeof import("../../app/member/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/preview/[sessionId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/preview/[sessionId]">> = Specific
  const handler = {} as typeof import("../../app/preview/[sessionId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/provider/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/provider">> = Specific
  const handler = {} as typeof import("../../app/provider/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
