import type { ApiCatalogEntry } from './api-catalog.types';

type SeedInput = Omit<
  ApiCatalogEntry,
  'id' | 'vendorSlug' | 'platformSlug'
>;

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function createEntry(input: SeedInput): ApiCatalogEntry {
  return {
    id: `${slugify(input.vendorName)}-${slugify(input.apiName)}`,
    vendorSlug: slugify(input.vendorName),
    platformSlug: slugify(input.platformName),
    ...input
  };
}

export const API_CATALOG_SEED: ApiCatalogEntry[] = [
  createEntry({
    vendorName: 'HealthEdge',
    platformName: 'HealthRules Payor',
    apiName: 'HealthRules Claims and Benefits APIs',
    apiCategory: 'Claims',
    apiSubcategory: 'Core Payer Administration',
    integrationDomain: 'Partner',
    strategicPriority: 'Critical',
    summary: 'Core payer administration surfaces for claims, benefits, and member operations.',
    description:
      'Strategic payer-core platform for claims adjudication, benefits configuration, and member administration connectivity.',
    supportedModules: ['Admin Console', 'Member Portal', 'Provider Portal', 'Billing and Enrollment'],
    primaryUsers: ['Platform Admin', 'Tenant Admin', 'Operations'],
    integrationPatterns: ['REST', 'EDI', 'Batch File'],
    authTypes: ['OAuth 2.0', 'API Key', 'Basic Auth'],
    dataStandards: ['JSON', 'X12 837', 'X12 835', 'X12 270/271', 'Proprietary'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Multi Tenant Template',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Blocker',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Internal Notes',
    lastReviewed: '2026-03-15',
    relatedModules: ['Admin Console', 'Billing and Enrollment', 'Support Tooling'],
    tags: ['payer-core', 'claims-adjudication', 'benefits'],
    notes: 'High-value payer migration target with broad downstream dependency impact.',
    futureAwsMapping: ['API Gateway', 'Step Functions', 'EventBridge'],
    canonicalModelMapping: ['Claim', 'BenefitPlan', 'MemberCoverage']
  }),
  createEntry({
    vendorName: 'GuidingCare',
    platformName: 'GuidingCare',
    apiName: 'Care Management APIs',
    apiCategory: 'Care Management',
    apiSubcategory: 'Utilization and Care Coordination',
    integrationDomain: 'Partner',
    strategicPriority: 'High',
    summary: 'Care management and utilization workflow surfaces for health plans.',
    description:
      'Catalog entry for care management, case management, assessments, and utilization review integrations.',
    supportedModules: ['Admin Console', 'Care Navigation', 'Support Tooling'],
    primaryUsers: ['Platform Admin', 'Tenant Admin', 'Support', 'Operations'],
    integrationPatterns: ['REST', 'Batch File'],
    authTypes: ['OAuth 2.0', 'API Key', 'Basic Auth'],
    dataStandards: ['JSON', 'FHIR R4', 'Proprietary'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Not Started',
    readinessLevel: 'Research',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Multi Tenant Template',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: false, alerts: true },
    documentationStatus: 'Internal Notes',
    lastReviewed: '2026-03-10',
    relatedModules: ['Admin Console', 'Care Navigation'],
    tags: ['care-management', 'um', 'case-management'],
    notes: 'Important to model early because workflows cross claims, auths, and member support.',
    futureAwsMapping: ['Lambda', 'Step Functions'],
    canonicalModelMapping: ['CarePlan', 'Authorization', 'Task']
  }),
  createEntry({
    vendorName: 'Cognizant TriZetto',
    platformName: 'Facets',
    apiName: 'Facets Claims and Enrollment APIs',
    apiCategory: 'Enrollment',
    apiSubcategory: 'Payer Core Enrollment',
    integrationDomain: 'Partner',
    strategicPriority: 'Critical',
    summary: 'Facets-driven enrollment, billing, and claim transaction connectivity.',
    description:
      'Core payer platform integration target supporting membership, enrollment, benefit, and claim exchange.',
    supportedModules: ['Admin Console', 'Shop and Enroll', 'Billing and Enrollment', 'Member Portal'],
    primaryUsers: ['Platform Admin', 'Tenant Admin', 'Operations'],
    integrationPatterns: ['REST', 'EDI', 'Batch File'],
    authTypes: ['API Key', 'Basic Auth', 'Bearer Token'],
    dataStandards: ['X12 837', 'X12 835', 'X12 270/271', 'CSV', 'JSON'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Multi Tenant Template',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Blocker',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-14',
    relatedModules: ['Shop and Enroll', 'Billing and Enrollment', 'Admin Console'],
    tags: ['facets', 'payer-core', 'enrollment'],
    notes: 'Critical for payer onboarding pathways and member lifecycle flows.',
    futureAwsMapping: ['API Gateway', 'SQS', 'Step Functions'],
    canonicalModelMapping: ['Enrollment', 'Invoice', 'Claim']
  }),
  createEntry({
    vendorName: 'Cognizant TriZetto',
    platformName: 'QNXT',
    apiName: 'QNXT Payer APIs',
    apiCategory: 'Benefits',
    apiSubcategory: 'Payer Administration',
    integrationDomain: 'Partner',
    strategicPriority: 'Critical',
    summary: 'QNXT payer administration endpoints for benefits, members, and claims.',
    description:
      'Strategic QNXT integration scaffold for payer administration use cases spanning benefits, members, and financial workflows.',
    supportedModules: ['Admin Console', 'Member Portal', 'Provider Portal', 'Billing and Enrollment'],
    primaryUsers: ['Platform Admin', 'Tenant Admin', 'Operations'],
    integrationPatterns: ['REST', 'EDI', 'Batch File'],
    authTypes: ['API Key', 'Basic Auth', 'Bearer Token'],
    dataStandards: ['JSON', 'X12 270/271', 'X12 837', 'X12 835'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Multi Tenant Template',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Blocker',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-12',
    relatedModules: ['Admin Console', 'Member Portal', 'Provider Portal'],
    tags: ['qnxt', 'payer-core', 'benefits'],
    notes: 'Needs canonical mapping discipline because implementations vary heavily by tenant.',
    futureAwsMapping: ['API Gateway', 'Lambda', 'EventBridge'],
    canonicalModelMapping: ['MemberCoverage', 'BenefitPlan', 'Claim']
  }),
  createEntry({
    vendorName: 'Epic',
    platformName: 'Epic',
    apiName: 'Epic FHIR APIs',
    apiCategory: 'Clinical',
    apiSubcategory: 'EHR Interoperability',
    integrationDomain: 'External',
    strategicPriority: 'Critical',
    summary: 'FHIR and SMART-based clinical interoperability surface for Epic-connected ecosystems.',
    description:
      'Enterprise clinical integration target for patient, encounter, appointment, and document exchange via FHIR.',
    supportedModules: ['Provider Portal', 'Member Portal', 'Admin Console', 'Care Navigation'],
    primaryUsers: ['Provider', 'Platform Admin', 'Support'],
    integrationPatterns: ['FHIR API', 'REST', 'Bulk Export'],
    authTypes: ['SMART on FHIR', 'OAuth 2.0', 'OpenID Connect'],
    dataStandards: ['FHIR R4', 'FHIR Bulk', 'JSON'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Partial',
    readinessLevel: 'Tenant Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Multi Tenant Template',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Implementation Guide Drafted',
    lastReviewed: '2026-03-18',
    relatedModules: ['Provider Portal', 'Member Portal', 'Care Navigation'],
    tags: ['ehr', 'fhir', 'clinical'],
    notes: 'Best treated as a flagship interoperability archetype for future tenant onboarding.',
    futureAwsMapping: ['API Gateway', 'HealthLake', 'EventBridge'],
    canonicalModelMapping: ['Patient', 'Encounter', 'Observation', 'Appointment']
  }),
  createEntry({
    vendorName: 'Oracle Health',
    platformName: 'Millennium',
    apiName: 'Cerner Millennium APIs',
    apiCategory: 'Clinical',
    apiSubcategory: 'EHR Interoperability',
    integrationDomain: 'External',
    strategicPriority: 'High',
    summary: 'Clinical data access and workflow APIs for Oracle Health / Cerner environments.',
    description:
      'Clinical interoperability target for Cerner/Oracle Health customers across provider and member experiences.',
    supportedModules: ['Provider Portal', 'Member Portal', 'Admin Console'],
    primaryUsers: ['Provider', 'Platform Admin', 'Support'],
    integrationPatterns: ['FHIR API', 'REST'],
    authTypes: ['SMART on FHIR', 'OAuth 2.0'],
    dataStandards: ['FHIR R4', 'HL7 v2', 'JSON'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Multi Tenant Template',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: false, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-11',
    relatedModules: ['Provider Portal', 'Member Portal'],
    tags: ['oracle-health', 'cerner', 'clinical'],
    notes: 'Important for hospital and integrated delivery system expansion.',
    futureAwsMapping: ['HealthLake', 'Lambda'],
    canonicalModelMapping: ['Patient', 'Encounter', 'DocumentReference']
  }),
  createEntry({
    vendorName: 'MEDITECH',
    platformName: 'Expanse',
    apiName: 'MEDITECH Expanse APIs',
    apiCategory: 'Clinical',
    apiSubcategory: 'Provider Clinical Integration',
    integrationDomain: 'External',
    strategicPriority: 'High',
    summary: 'Clinical integration scaffolding for MEDITECH Expanse environments.',
    description:
      'Provider-facing interoperability surface for clinical data access, documentation exchange, and scheduling context.',
    supportedModules: ['Provider Portal', 'Member Portal'],
    primaryUsers: ['Provider', 'Platform Admin'],
    integrationPatterns: ['FHIR API', 'REST'],
    authTypes: ['OAuth 2.0', 'SMART on FHIR'],
    dataStandards: ['FHIR R4', 'HL7 v2'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Not Started',
    readinessLevel: 'Research',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Single Tenant',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Helpful',
    observabilitySupport: { healthChecks: true, logs: false, metrics: false, alerts: false },
    documentationStatus: 'Internal Notes',
    lastReviewed: '2026-03-05',
    relatedModules: ['Provider Portal'],
    tags: ['meditech', 'ehr', 'provider'],
    notes: 'Targeted regional health system opportunity rather than universal first-wave priority.',
    futureAwsMapping: ['HealthLake'],
    canonicalModelMapping: ['Patient', 'Encounter']
  }),
  createEntry({
    vendorName: 'Availity',
    platformName: 'Availity Essentials',
    apiName: 'Eligibility and Payer APIs',
    apiCategory: 'Eligibility',
    apiSubcategory: 'Provider Revenue Cycle',
    integrationDomain: 'Partner',
    strategicPriority: 'Critical',
    summary: 'Eligibility and payer communication APIs widely used in provider workflows.',
    description:
      'High-value provider workflow target for eligibility, authorization routing, and payer communications.',
    supportedModules: ['Provider Portal', 'Admin Console', 'Support Tooling'],
    primaryUsers: ['Provider', 'Operations', 'Platform Admin'],
    integrationPatterns: ['REST', 'EDI'],
    authTypes: ['API Key', 'OAuth 2.0'],
    dataStandards: ['JSON', 'X12 270/271', 'X12 278'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Implemented',
    readinessLevel: 'Operational',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Multi Tenant Template',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Blocker',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Operationalized',
    lastReviewed: '2026-03-18',
    relatedModules: ['Provider Portal', 'Admin Console'],
    tags: ['eligibility', 'payer-network', 'provider'],
    notes: 'One of the strongest candidates for productized tenant enablement.',
    futureAwsMapping: ['API Gateway', 'CloudWatch', 'Step Functions'],
    canonicalModelMapping: ['EligibilityCheck', 'AuthorizationRequest']
  }),
  createEntry({
    vendorName: 'Change Healthcare',
    platformName: 'Payer and Provider APIs',
    apiName: 'Claims and Eligibility APIs',
    apiCategory: 'Claims',
    apiSubcategory: 'Clearinghouse',
    integrationDomain: 'Partner',
    strategicPriority: 'Critical',
    summary: 'Broad clearinghouse and claim connectivity surface for payer/provider transactions.',
    description:
      'Major claims, remittance, and eligibility network for provider and payer integrations.',
    supportedModules: ['Provider Portal', 'Admin Console', 'Support Tooling', 'Billing and Enrollment'],
    primaryUsers: ['Provider', 'Operations', 'Platform Admin'],
    integrationPatterns: ['EDI', 'REST', 'Batch File'],
    authTypes: ['API Key', 'Basic Auth', 'Bearer Token'],
    dataStandards: ['X12 837', 'X12 835', 'X12 270/271', 'X12 276/277'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Blocker',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-17',
    relatedModules: ['Provider Portal', 'Admin Console', 'Support Tooling'],
    tags: ['clearinghouse', 'claims', 'edi'],
    notes: 'Needs careful operational posture because outage risk materially affects support workflows.',
    futureAwsMapping: ['SQS', 'Step Functions', 'CloudWatch'],
    canonicalModelMapping: ['ClaimSubmission', 'ClaimStatus', 'Remittance']
  }),
  createEntry({
    vendorName: 'Zelis',
    platformName: 'Zelis Payments Platform',
    apiName: 'Payments and Repricing APIs',
    apiCategory: 'Payments',
    apiSubcategory: 'Provider Payments',
    integrationDomain: 'Partner',
    strategicPriority: 'High',
    summary: 'Provider payments and pricing workflow integration surface.',
    description:
      'Payment status, remittance, and pricing connectivity target for payer/provider financial workflows.',
    supportedModules: ['Provider Portal', 'Admin Console', 'Billing and Enrollment'],
    primaryUsers: ['Provider', 'Operations', 'Platform Admin'],
    integrationPatterns: ['REST', 'Batch File'],
    authTypes: ['OAuth 2.0', 'API Key'],
    dataStandards: ['JSON', 'X12 835', 'CSV'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Single Tenant',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: false, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-09',
    relatedModules: ['Provider Portal', 'Admin Console'],
    tags: ['payments', 'repricing', 'provider-finance'],
    notes: 'Best positioned as an optional provider financial services accelerator.',
    futureAwsMapping: ['Lambda', 'CloudWatch'],
    canonicalModelMapping: ['Payment', 'Remittance']
  }),
  createEntry({
    vendorName: 'Waystar',
    platformName: 'Waystar',
    apiName: 'Revenue Cycle APIs',
    apiCategory: 'Billing',
    apiSubcategory: 'Revenue Cycle Automation',
    integrationDomain: 'Partner',
    strategicPriority: 'High',
    summary: 'RCM automation APIs for claims, denials, and payments workflows.',
    description:
      'Revenue cycle integration target for provider and billing operations, especially denial and claims follow-up.',
    supportedModules: ['Provider Portal', 'Admin Console', 'Support Tooling'],
    primaryUsers: ['Provider', 'Operations', 'Support'],
    integrationPatterns: ['REST', 'EDI', 'Batch File'],
    authTypes: ['OAuth 2.0', 'API Key'],
    dataStandards: ['JSON', 'X12 837', 'X12 835', 'X12 276/277'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Not Started',
    readinessLevel: 'Research',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Single Tenant',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Helpful',
    observabilitySupport: { healthChecks: true, logs: false, metrics: false, alerts: true },
    documentationStatus: 'Internal Notes',
    lastReviewed: '2026-03-08',
    relatedModules: ['Provider Portal', 'Admin Console'],
    tags: ['rcm', 'claims-follow-up', 'payments'],
    notes: 'Good candidate once provider portal collections workflows deepen.',
    futureAwsMapping: ['Step Functions'],
    canonicalModelMapping: ['ClaimStatus', 'Task']
  }),
  createEntry({
    vendorName: 'Surescripts',
    platformName: 'Surescripts Network',
    apiName: 'Prescription and Pharmacy APIs',
    apiCategory: 'Pharmacy',
    apiSubcategory: 'ePrescribing Network',
    integrationDomain: 'External',
    strategicPriority: 'High',
    summary: 'Medication, formulary, and prescription exchange network.',
    description:
      'Strategic pharmacy and medication history integration point for care and provider experiences.',
    supportedModules: ['Provider Portal', 'Member Portal', 'Care Navigation'],
    primaryUsers: ['Provider', 'Member', 'Platform Admin'],
    integrationPatterns: ['REST', 'Batch File'],
    authTypes: ['OAuth 2.0', 'mTLS'],
    dataStandards: ['JSON', 'NCPDP', 'Proprietary'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: false,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: false, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-16',
    relatedModules: ['Provider Portal', 'Member Portal'],
    tags: ['pharmacy', 'eprescribing', 'medication'],
    notes: 'Requires careful product scoping due network participation and compliance dependencies.',
    futureAwsMapping: ['API Gateway', 'Secrets Manager'],
    canonicalModelMapping: ['MedicationRequest', 'Formulary', 'MedicationHistory']
  }),
  createEntry({
    vendorName: 'Express Scripts',
    platformName: 'Express Scripts PBM',
    apiName: 'PBM Eligibility and Formulary APIs',
    apiCategory: 'Pharmacy',
    apiSubcategory: 'PBM Integration',
    integrationDomain: 'Partner',
    strategicPriority: 'High',
    summary: 'PBM eligibility, formulary, and benefit surfaces for member and provider workflows.',
    description:
      'Tenant-configurable PBM integration target for formulary lookup, member pharmacy benefits, and utilization workflows.',
    supportedModules: ['Member Portal', 'Provider Portal', 'Admin Console'],
    primaryUsers: ['Member', 'Provider', 'Tenant Admin'],
    integrationPatterns: ['REST', 'Batch File'],
    authTypes: ['API Key', 'OAuth 2.0'],
    dataStandards: ['JSON', 'NCPDP', 'CSV'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Not Started',
    readinessLevel: 'Research',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Single Tenant',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Helpful',
    observabilitySupport: { healthChecks: true, logs: false, metrics: false, alerts: true },
    documentationStatus: 'Internal Notes',
    lastReviewed: '2026-03-07',
    relatedModules: ['Member Portal', 'Provider Portal'],
    tags: ['pbm', 'formulary', 'pharmacy-benefits'],
    notes: 'Useful for payer-specific pharmacy differentiation but needs business validation by tenant.',
    futureAwsMapping: ['Secrets Manager'],
    canonicalModelMapping: ['PharmacyBenefit', 'Formulary']
  }),
  createEntry({
    vendorName: 'CVS Caremark',
    platformName: 'Caremark APIs',
    apiName: 'PBM Benefit APIs',
    apiCategory: 'Pharmacy',
    apiSubcategory: 'PBM Integration',
    integrationDomain: 'Partner',
    strategicPriority: 'High',
    summary: 'Member pharmacy benefit and formulary service integration.',
    description:
      'PBM integration target supporting pharmacy benefit lookups, eligibility, and pricing workflows.',
    supportedModules: ['Member Portal', 'Provider Portal', 'Admin Console'],
    primaryUsers: ['Member', 'Provider', 'Tenant Admin'],
    integrationPatterns: ['REST'],
    authTypes: ['OAuth 2.0', 'API Key'],
    dataStandards: ['JSON', 'NCPDP'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Not Started',
    readinessLevel: 'Research',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Single Tenant',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Helpful',
    observabilitySupport: { healthChecks: true, logs: false, metrics: false, alerts: true },
    documentationStatus: 'Internal Notes',
    lastReviewed: '2026-03-07',
    relatedModules: ['Member Portal', 'Provider Portal'],
    tags: ['pbm', 'caremark', 'pharmacy'],
    notes: 'Keep model aligned with Express Scripts and OptumRx for template reuse.',
    futureAwsMapping: ['Secrets Manager'],
    canonicalModelMapping: ['PharmacyBenefit', 'MedicationPrice']
  }),
  createEntry({
    vendorName: 'Optum',
    platformName: 'OptumRx',
    apiName: 'OptumRx Pharmacy APIs',
    apiCategory: 'Pharmacy',
    apiSubcategory: 'PBM Integration',
    integrationDomain: 'Partner',
    strategicPriority: 'High',
    summary: 'PBM APIs for formulary, pricing, and member pharmacy benefit workflows.',
    description:
      'Third PBM archetype in the catalog to support payer-specific pharmacy strategy and future tenant enablement.',
    supportedModules: ['Member Portal', 'Provider Portal', 'Admin Console'],
    primaryUsers: ['Member', 'Provider', 'Tenant Admin'],
    integrationPatterns: ['REST'],
    authTypes: ['OAuth 2.0', 'API Key'],
    dataStandards: ['JSON', 'NCPDP'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Not Started',
    readinessLevel: 'Research',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Single Tenant',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Helpful',
    observabilitySupport: { healthChecks: true, logs: false, metrics: false, alerts: true },
    documentationStatus: 'Internal Notes',
    lastReviewed: '2026-03-07',
    relatedModules: ['Member Portal', 'Provider Portal'],
    tags: ['pbm', 'optumrx', 'pharmacy'],
    notes: 'Supports future payer-side PBM normalization strategy.',
    futureAwsMapping: ['Secrets Manager'],
    canonicalModelMapping: ['PharmacyBenefit', 'MedicationPrice']
  }),
  createEntry({
    vendorName: 'Salesforce',
    platformName: 'Health Cloud',
    apiName: 'CRM and Engagement APIs',
    apiCategory: 'CRM / Engagement',
    apiSubcategory: 'Member and Service Cloud',
    integrationDomain: 'Platform',
    strategicPriority: 'High',
    summary: 'CRM and service workflow integrations for member, support, and broker journeys.',
    description:
      'Strong candidate for support tooling, outreach, lead management, and care engagement workflows.',
    supportedModules: ['Admin Console', 'Broker Portal', 'Employer Portal', 'Support Tooling'],
    primaryUsers: ['Support', 'Broker', 'Employer', 'Platform Admin'],
    integrationPatterns: ['REST', 'Webhook', 'Event Stream'],
    authTypes: ['OAuth 2.0', 'Bearer Token'],
    dataStandards: ['JSON', 'Webhook'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Partial',
    readinessLevel: 'Tenant Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Multi Tenant Template',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Implementation Guide Drafted',
    lastReviewed: '2026-03-18',
    relatedModules: ['Admin Console', 'Broker Portal', 'Employer Portal'],
    tags: ['crm', 'engagement', 'service-cloud'],
    notes: 'High leverage for operational support and sales-to-service workflows.',
    futureAwsMapping: ['EventBridge', 'Lambda', 'SQS'],
    canonicalModelMapping: ['Case', 'Contact', 'CareProgramEnrollment']
  }),
  createEntry({
    vendorName: 'mPulse',
    platformName: 'mPulse Engagement Platform',
    apiName: 'Outreach and Engagement APIs',
    apiCategory: 'CRM / Engagement',
    apiSubcategory: 'Member Outreach',
    integrationDomain: 'Partner',
    strategicPriority: 'Medium',
    summary: 'Member outreach, campaigns, and engagement orchestration APIs.',
    description:
      'Supports outreach campaigns, member nudges, and communications orchestration for health plans.',
    supportedModules: ['Notifications', 'Member Portal', 'Admin Console'],
    primaryUsers: ['Operations', 'Support', 'Tenant Admin'],
    integrationPatterns: ['REST', 'Webhook'],
    authTypes: ['OAuth 2.0', 'API Key'],
    dataStandards: ['JSON', 'Webhook'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Mocked',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Single Tenant',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Helpful',
    observabilitySupport: { healthChecks: true, logs: false, metrics: true, alerts: false },
    documentationStatus: 'Internal Notes',
    lastReviewed: '2026-03-06',
    relatedModules: ['Notifications', 'Admin Console'],
    tags: ['engagement', 'campaigns', 'outreach'],
    notes: 'Useful for marketing and care gap outreach, but not an AWS migration blocker.',
    futureAwsMapping: ['Pinpoint', 'EventBridge'],
    canonicalModelMapping: ['Communication', 'Campaign', 'Member']
  }),
  createEntry({
    vendorName: 'Twilio',
    platformName: 'Twilio Messaging and Verify',
    apiName: 'Messaging and Identity APIs',
    apiCategory: 'Identity',
    apiSubcategory: 'Messaging and Verification',
    integrationDomain: 'Platform',
    strategicPriority: 'High',
    summary: 'SMS, voice, and verification APIs for communications and identity confirmation.',
    description:
      'Platform-level messaging and verification dependency supporting OTP, outreach, and notification workflows.',
    supportedModules: ['Notifications', 'Member Portal', 'Admin Console', 'Support Tooling'],
    primaryUsers: ['Member', 'Support', 'Platform Admin'],
    integrationPatterns: ['REST', 'Webhook'],
    authTypes: ['API Key', 'Bearer Token'],
    dataStandards: ['JSON', 'Webhook'],
    deploymentModel: 'Platform Service',
    implementationStatus: 'Implemented',
    readinessLevel: 'Operational',
    tenantConfigurable: false,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Operationalized',
    lastReviewed: '2026-03-17',
    relatedModules: ['Notifications', 'Admin Console', 'Support Tooling'],
    tags: ['messaging', 'otp', 'verification'],
    notes: 'Likely to stay platform-managed instead of tenant-managed.',
    futureAwsMapping: ['SNS', 'EventBridge', 'Secrets Manager'],
    canonicalModelMapping: ['Notification', 'UserVerification']
  }),
  createEntry({
    vendorName: 'Amwell',
    platformName: 'Amwell',
    apiName: 'Virtual Care APIs',
    apiCategory: 'Clinical',
    apiSubcategory: 'Telehealth',
    integrationDomain: 'Partner',
    strategicPriority: 'Medium',
    summary: 'Virtual care session, appointment, and telehealth engagement APIs.',
    description:
      'Telehealth integration target for member navigation and provider digital care workflows.',
    supportedModules: ['Member Portal', 'Provider Portal', 'Care Navigation'],
    primaryUsers: ['Member', 'Provider', 'Tenant Admin'],
    integrationPatterns: ['REST', 'Webhook'],
    authTypes: ['OAuth 2.0', 'Bearer Token'],
    dataStandards: ['JSON', 'FHIR R4'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Not Started',
    readinessLevel: 'Research',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Single Tenant',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Future',
    observabilitySupport: { healthChecks: true, logs: false, metrics: false, alerts: false },
    documentationStatus: 'Internal Notes',
    lastReviewed: '2026-03-04',
    relatedModules: ['Member Portal', 'Provider Portal', 'Care Navigation'],
    tags: ['telehealth', 'virtual-care', 'appointments'],
    notes: 'Strategic future experience layer rather than core migration blocker.',
    futureAwsMapping: ['Chime SDK', 'EventBridge'],
    canonicalModelMapping: ['Appointment', 'Encounter']
  }),
  createEntry({
    vendorName: 'Snowflake',
    platformName: 'Snowflake',
    apiName: 'Data Sharing and Warehouse APIs',
    apiCategory: 'Analytics',
    apiSubcategory: 'Data Platform',
    integrationDomain: 'Platform',
    strategicPriority: 'High',
    summary: 'Analytic data platform for cross-tenant exports, reporting, and data sharing.',
    description:
      'Key analytics and downstream data operations target for data product delivery, exports, and tenant-specific marts.',
    supportedModules: ['Admin Console', 'Support Tooling'],
    primaryUsers: ['Platform Admin', 'Engineering', 'Operations'],
    integrationPatterns: ['REST', 'Database Share', 'Batch File'],
    authTypes: ['OAuth 2.0', 'Bearer Token', 'Basic Auth'],
    dataStandards: ['JSON', 'CSV', 'Proprietary'],
    deploymentModel: 'Platform Service',
    implementationStatus: 'Partial',
    readinessLevel: 'Tenant Ready',
    tenantConfigurable: false,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Implementation Guide Drafted',
    lastReviewed: '2026-03-13',
    relatedModules: ['Admin Console', 'Support Tooling'],
    tags: ['analytics', 'warehouse', 'data-sharing'],
    notes: 'Likely to be paired with canonical-model exports and observability sinks.',
    futureAwsMapping: ['Glue', 'S3', 'Lambda'],
    canonicalModelMapping: ['Claim', 'Member', 'Provider', 'Invoice']
  }),
  createEntry({
    vendorName: 'Databricks',
    platformName: 'Databricks Lakehouse',
    apiName: 'Lakehouse and AI APIs',
    apiCategory: 'Analytics',
    apiSubcategory: 'Data Engineering',
    integrationDomain: 'Platform',
    strategicPriority: 'Medium',
    summary: 'Data engineering and advanced analytics target for enterprise data pipelines.',
    description:
      'Lakehouse analytics and downstream ML enablement entry for large-enterprise data workflows.',
    supportedModules: ['Admin Console', 'Support Tooling'],
    primaryUsers: ['Engineering', 'Platform Admin', 'Operations'],
    integrationPatterns: ['REST', 'Batch File', 'Database Share'],
    authTypes: ['OAuth 2.0', 'Bearer Token'],
    dataStandards: ['JSON', 'CSV', 'Proprietary'],
    deploymentModel: 'Platform Service',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: false,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Helpful',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Internal Notes',
    lastReviewed: '2026-03-03',
    relatedModules: ['Admin Console'],
    tags: ['analytics', 'lakehouse', 'data-engineering'],
    notes: 'Useful for larger data-product strategies but secondary to baseline operational migration.',
    futureAwsMapping: ['EMR', 'Glue', 'S3'],
    canonicalModelMapping: ['Canonical Lakehouse Models']
  }),
  createEntry({
    vendorName: 'AWS',
    platformName: 'HealthLake',
    apiName: 'HealthLake FHIR APIs',
    apiCategory: 'Interoperability',
    apiSubcategory: 'FHIR Repository',
    integrationDomain: 'Platform',
    strategicPriority: 'High',
    summary: 'Managed FHIR store and analytics target for AWS-native healthcare data services.',
    description:
      'Important future-state AWS alignment surface for normalized FHIR data, search, and longitudinal patient context.',
    supportedModules: ['Admin Console', 'Member Portal', 'Provider Portal', 'Care Navigation'],
    primaryUsers: ['Engineering', 'Platform Admin'],
    integrationPatterns: ['FHIR API', 'Bulk Export', 'REST'],
    authTypes: ['OAuth 2.0', 'Bearer Token'],
    dataStandards: ['FHIR R4', 'FHIR Bulk', 'JSON'],
    deploymentModel: 'Platform Service',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: false,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Blocker',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-18',
    relatedModules: ['Admin Console', 'Provider Portal', 'Member Portal'],
    tags: ['aws', 'healthlake', 'fhir'],
    notes: 'Important architectural anchor for AWS migration planning and canonical clinical models.',
    futureAwsMapping: ['HealthLake', 'IAM', 'CloudWatch'],
    canonicalModelMapping: ['Patient', 'Coverage', 'Claim', 'Observation']
  }),
  createEntry({
    vendorName: 'Google Cloud',
    platformName: 'Healthcare API',
    apiName: 'Google Cloud Healthcare API',
    apiCategory: 'Interoperability',
    apiSubcategory: 'FHIR and HL7 Repository',
    integrationDomain: 'Platform',
    strategicPriority: 'Low',
    summary: 'Comparable cloud healthcare API target for competitive analysis and future portability.',
    description:
      'Useful catalog reference for competitive positioning and portability planning, though not a near-term AWS dependency.',
    supportedModules: ['Admin Console'],
    primaryUsers: ['Engineering', 'Platform Admin'],
    integrationPatterns: ['FHIR API', 'REST', 'Bulk Export'],
    authTypes: ['OAuth 2.0', 'Bearer Token'],
    dataStandards: ['FHIR R4', 'HL7 v2', 'JSON'],
    deploymentModel: 'Platform Service',
    implementationStatus: 'Not Started',
    readinessLevel: 'Research',
    tenantConfigurable: false,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Future',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-02',
    relatedModules: ['Admin Console'],
    tags: ['gcp', 'fhir', 'cloud'],
    notes: 'Valuable for benchmarking but not core to AWS migration execution.',
    futureAwsMapping: ['HealthLake'],
    canonicalModelMapping: ['Patient', 'Encounter', 'Observation']
  }),
  createEntry({
    vendorName: 'Redox',
    platformName: 'Redox',
    apiName: 'Interoperability Exchange APIs',
    apiCategory: 'Interoperability',
    apiSubcategory: 'Clinical and Administrative Exchange',
    integrationDomain: 'Partner',
    strategicPriority: 'High',
    summary: 'Healthcare integration exchange for EHR, scheduling, and messaging workflows.',
    description:
      'Acceleration layer for interoperability work when direct EHR/vendor integrations are too costly or slow.',
    supportedModules: ['Provider Portal', 'Admin Console', 'Care Navigation'],
    primaryUsers: ['Platform Admin', 'Engineering', 'Support'],
    integrationPatterns: ['REST', 'FHIR API', 'Webhook'],
    authTypes: ['OAuth 2.0', 'API Key'],
    dataStandards: ['FHIR R4', 'HL7 v2', 'JSON', 'Webhook'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: false, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-12',
    relatedModules: ['Provider Portal', 'Admin Console'],
    tags: ['interop', 'redox', 'ehr'],
    notes: 'Useful bridge strategy for multi-vendor interoperability.',
    futureAwsMapping: ['API Gateway', 'EventBridge'],
    canonicalModelMapping: ['Patient', 'Encounter', 'Appointment']
  }),
  createEntry({
    vendorName: '1upHealth',
    platformName: '1upHealth FHIR Platform',
    apiName: 'FHIR Data Platform APIs',
    apiCategory: 'Interoperability',
    apiSubcategory: 'Payer and Provider Data Access',
    integrationDomain: 'Partner',
    strategicPriority: 'Medium',
    summary: 'FHIR aggregation platform for payer and provider healthcare data exchange.',
    description:
      'Potential accelerator for CMS interoperability use cases and patient-mediated access patterns.',
    supportedModules: ['Member Portal', 'Admin Console', 'Care Navigation'],
    primaryUsers: ['Member', 'Platform Admin', 'Engineering'],
    integrationPatterns: ['FHIR API', 'Bulk Export', 'REST'],
    authTypes: ['OAuth 2.0', 'OpenID Connect'],
    dataStandards: ['FHIR R4', 'FHIR Bulk', 'JSON'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Not Started',
    readinessLevel: 'Research',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Helpful',
    observabilitySupport: { healthChecks: true, logs: false, metrics: false, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-02',
    relatedModules: ['Member Portal', 'Admin Console'],
    tags: ['fhir', 'cms-interop', 'aggregator'],
    notes: 'Strong fit for future member-access and payer data portability strategies.',
    futureAwsMapping: ['HealthLake', 'Lambda'],
    canonicalModelMapping: ['Patient', 'Coverage', 'ExplanationOfBenefit']
  }),
  createEntry({
    vendorName: 'CoverMyMeds',
    platformName: 'CoverMyMeds',
    apiName: 'Prior Authorization APIs',
    apiCategory: 'Prior Authorization',
    apiSubcategory: 'Medication Prior Auth',
    integrationDomain: 'Partner',
    strategicPriority: 'High',
    summary: 'Prior authorization workflows for medication and specialty pharmacy scenarios.',
    description:
      'Strong prior authorization target for provider operations and member pharmacy workflows.',
    supportedModules: ['Provider Portal', 'Member Portal', 'Admin Console'],
    primaryUsers: ['Provider', 'Member', 'Operations'],
    integrationPatterns: ['REST', 'Webhook'],
    authTypes: ['OAuth 2.0', 'API Key'],
    dataStandards: ['JSON', 'NCPDP'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Single Tenant',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: false, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-11',
    relatedModules: ['Provider Portal', 'Admin Console'],
    tags: ['prior-auth', 'pharmacy', 'provider-workflow'],
    notes: 'Important for reducing provider abrasion in medication workflows.',
    futureAwsMapping: ['Step Functions', 'EventBridge'],
    canonicalModelMapping: ['AuthorizationRequest', 'MedicationRequest']
  }),
  createEntry({
    vendorName: 'Bamboo Health',
    platformName: 'Bamboo Health',
    apiName: 'Care Events and Network APIs',
    apiCategory: 'Care Management',
    apiSubcategory: 'Care Event Notification',
    integrationDomain: 'Partner',
    strategicPriority: 'Medium',
    summary: 'Admission, discharge, transfer, and care event notifications.',
    description:
      'Useful care coordination and eventing integration target for health plans and support workflows.',
    supportedModules: ['Care Navigation', 'Admin Console', 'Support Tooling'],
    primaryUsers: ['Support', 'Operations', 'Platform Admin'],
    integrationPatterns: ['REST', 'Webhook', 'Event Stream'],
    authTypes: ['OAuth 2.0', 'API Key'],
    dataStandards: ['JSON', 'HL7 v2', 'Webhook'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Not Started',
    readinessLevel: 'Research',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Single Tenant',
    environmentSupport: { sandbox: false, test: true, production: true },
    awsRelevance: 'Helpful',
    observabilitySupport: { healthChecks: true, logs: false, metrics: false, alerts: true },
    documentationStatus: 'Internal Notes',
    lastReviewed: '2026-03-01',
    relatedModules: ['Care Navigation', 'Admin Console'],
    tags: ['care-events', 'adt', 'care-coordination'],
    notes: 'Good follow-on opportunity after claims and clinical core surfaces are stronger.',
    futureAwsMapping: ['EventBridge', 'Lambda'],
    canonicalModelMapping: ['EncounterEvent', 'CareTransition']
  }),
  createEntry({
    vendorName: 'Okta',
    platformName: 'Okta Workforce Identity',
    apiName: 'Identity and SSO APIs',
    apiCategory: 'Identity',
    apiSubcategory: 'SSO and Provisioning',
    integrationDomain: 'Platform',
    strategicPriority: 'High',
    summary: 'Identity provider integration for admin and tenant SSO enablement.',
    description:
      'Control-plane identity and federation target for admin security, tenant onboarding, and access management.',
    supportedModules: ['Admin Console', 'Provider Portal', 'Employer Portal', 'Broker Portal'],
    primaryUsers: ['Platform Admin', 'Tenant Admin', 'Engineering'],
    integrationPatterns: ['REST', 'Webhook'],
    authTypes: ['OpenID Connect', 'SAML', 'OAuth 2.0'],
    dataStandards: ['JSON', 'Webhook'],
    deploymentModel: 'Platform Service',
    implementationStatus: 'Partial',
    readinessLevel: 'Tenant Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Implementation Guide Drafted',
    lastReviewed: '2026-03-18',
    relatedModules: ['Admin Console', 'Provider Portal', 'Employer Portal', 'Broker Portal'],
    tags: ['identity', 'sso', 'provisioning'],
    notes: 'Important security control-plane dependency, especially pre-migration.',
    futureAwsMapping: ['IAM Identity Center', 'Cognito'],
    canonicalModelMapping: ['IdentityProvider', 'UserSession']
  }),
  createEntry({
    vendorName: 'Datadog',
    platformName: 'Datadog',
    apiName: 'Observability APIs',
    apiCategory: 'Observability',
    apiSubcategory: 'Monitoring and Alerting',
    integrationDomain: 'Platform',
    strategicPriority: 'High',
    summary: 'Operational telemetry, metrics, logs, and alert routing APIs.',
    description:
      'Important operational platform dependency for production monitoring and admin readiness.',
    supportedModules: ['Admin Console', 'Support Tooling'],
    primaryUsers: ['Platform Admin', 'Operations', 'Engineering'],
    integrationPatterns: ['REST', 'Webhook', 'Event Stream'],
    authTypes: ['API Key', 'Bearer Token'],
    dataStandards: ['JSON', 'Webhook'],
    deploymentModel: 'Platform Service',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: false,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Blocker',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-18',
    relatedModules: ['Admin Console', 'Support Tooling'],
    tags: ['observability', 'alerts', 'monitoring'],
    notes: 'Either Datadog or AWS-native observability will need a first-class operational story.',
    futureAwsMapping: ['CloudWatch', 'X-Ray', 'EventBridge'],
    canonicalModelMapping: ['HealthCheck', 'Alert', 'OperationalEvent']
  }),
  createEntry({
    vendorName: 'MuleSoft',
    platformName: 'Anypoint Platform',
    apiName: 'Integration Platform APIs',
    apiCategory: 'Admin',
    apiSubcategory: 'API Orchestration',
    integrationDomain: 'Platform',
    strategicPriority: 'Medium',
    summary: 'General API orchestration and mediation layer for partner onboarding.',
    description:
      'A useful catalog archetype for mediated partner integrations and future API productization.',
    supportedModules: ['Admin Console', 'Support Tooling'],
    primaryUsers: ['Platform Admin', 'Engineering'],
    integrationPatterns: ['REST', 'Webhook', 'Event Stream', 'Batch File'],
    authTypes: ['OAuth 2.0', 'API Key', 'Basic Auth'],
    dataStandards: ['JSON', 'Webhook', 'CSV', 'Proprietary'],
    deploymentModel: 'Hybrid',
    implementationStatus: 'Not Started',
    readinessLevel: 'Research',
    tenantConfigurable: false,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Helpful',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-01',
    relatedModules: ['Admin Console'],
    tags: ['integration-platform', 'orchestration', 'middleware'],
    notes: 'Helpful reference architecture entry even if we stay lighter-weight internally.',
    futureAwsMapping: ['API Gateway', 'Lambda', 'Step Functions'],
    canonicalModelMapping: ['PartnerIntegration']
  }),
  createEntry({
    vendorName: 'DocuSign',
    platformName: 'DocuSign',
    apiName: 'Document and eSignature APIs',
    apiCategory: 'Documents',
    apiSubcategory: 'eSignature and Forms',
    integrationDomain: 'Partner',
    strategicPriority: 'Medium',
    summary: 'Digital forms and eSignature workflows for enrollment and admin operations.',
    description:
      'Document-centric integration target for enrollment forms, employer paperwork, and administrative approvals.',
    supportedModules: ['Shop and Enroll', 'Employer Portal', 'Admin Console', 'Broker Portal'],
    primaryUsers: ['Employer', 'Broker', 'Tenant Admin', 'Support'],
    integrationPatterns: ['REST', 'Webhook'],
    authTypes: ['OAuth 2.0', 'Bearer Token'],
    dataStandards: ['JSON', 'Webhook'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Mocked',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Single Tenant',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Helpful',
    observabilitySupport: { healthChecks: true, logs: true, metrics: false, alerts: true },
    documentationStatus: 'Internal Notes',
    lastReviewed: '2026-03-05',
    relatedModules: ['Shop and Enroll', 'Employer Portal', 'Broker Portal'],
    tags: ['documents', 'esignature', 'forms'],
    notes: 'Useful customer-facing differentiator but not pre-AWS critical.',
    futureAwsMapping: ['S3', 'Step Functions'],
    canonicalModelMapping: ['Document', 'SignatureRequest']
  }),
  createEntry({
    vendorName: 'Edifecs',
    platformName: 'Edifecs Interoperability Cloud',
    apiName: 'FHIR and Interoperability APIs',
    apiCategory: 'Interoperability',
    apiSubcategory: 'FHIR Exchange and Data Quality',
    integrationDomain: 'Partner',
    strategicPriority: 'High',
    summary: 'FHIR interoperability, validation, and exchange services for payer and provider ecosystems.',
    description:
      'Strategic interoperability target for FHIR exchange, data quality checks, and clinical-administrative translation across external healthcare systems.',
    supportedModules: ['Admin Console', 'Provider Portal', 'Member Portal', 'Care Navigation'],
    primaryUsers: ['Platform Admin', 'Engineering', 'Support'],
    integrationPatterns: ['FHIR API', 'REST', 'Event Stream'],
    authTypes: ['OAuth 2.0', 'OpenID Connect', 'Bearer Token'],
    dataStandards: ['FHIR R4', 'HL7 v2', 'JSON', 'Proprietary'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Platform Managed',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-19',
    relatedModules: ['Admin Console', 'Provider Portal', 'Care Navigation'],
    tags: ['edifecs', 'fhir', 'interop', 'data-quality'],
    notes: 'Strong candidate for enterprise interoperability programs where direct EHR or payer-core integration needs mediation and data normalization.',
    futureAwsMapping: ['API Gateway', 'HealthLake', 'EventBridge'],
    canonicalModelMapping: ['Patient', 'Coverage', 'Claim', 'DocumentReference']
  }),
  createEntry({
    vendorName: 'Edifecs',
    platformName: 'Edifecs Prior Authorization Suite',
    apiName: 'Prior Authorization and UM APIs',
    apiCategory: 'Prior Authorization',
    apiSubcategory: 'Utilization Management',
    integrationDomain: 'Partner',
    strategicPriority: 'High',
    summary: 'Prior authorization, utilization management, and clinical review workflow APIs.',
    description:
      'Important prior authorization and utilization management target for provider workflows, payer operations, and automation of review decisions.',
    supportedModules: ['Provider Portal', 'Admin Console', 'Care Navigation', 'Support Tooling'],
    primaryUsers: ['Provider', 'Operations', 'Platform Admin', 'Support'],
    integrationPatterns: ['REST', 'Webhook', 'EDI'],
    authTypes: ['OAuth 2.0', 'API Key', 'Bearer Token'],
    dataStandards: ['JSON', 'X12 278', 'FHIR R4', 'Webhook'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Multi Tenant Template',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-19',
    relatedModules: ['Provider Portal', 'Admin Console', 'Care Navigation'],
    tags: ['edifecs', 'prior-auth', 'um', 'x12-278'],
    notes: 'Useful where payers want to modernize prior authorization and automate clinical review orchestration without rebuilding all UM logic internally.',
    futureAwsMapping: ['Step Functions', 'EventBridge', 'CloudWatch'],
    canonicalModelMapping: ['AuthorizationRequest', 'Task', 'ClinicalReview']
  }),
  createEntry({
    vendorName: 'Edifecs',
    platformName: 'Edifecs Payer and Provider Exchange',
    apiName: 'Claims and Eligibility APIs',
    apiCategory: 'Claims',
    apiSubcategory: 'Payer / Provider Administrative Exchange',
    integrationDomain: 'Partner',
    strategicPriority: 'High',
    summary: 'Administrative healthcare exchange APIs for claims, eligibility, and payer/provider connectivity.',
    description:
      'Administrative integration surface for payer-provider transaction exchange, data validation, and modernized claims and eligibility workflows.',
    supportedModules: ['Provider Portal', 'Admin Console', 'Billing and Enrollment', 'Support Tooling'],
    primaryUsers: ['Provider', 'Operations', 'Platform Admin'],
    integrationPatterns: ['REST', 'EDI', 'Batch File'],
    authTypes: ['API Key', 'OAuth 2.0', 'Basic Auth'],
    dataStandards: ['X12 270/271', 'X12 276/277', 'X12 837', 'X12 835', 'JSON'],
    deploymentModel: 'Vendor SaaS',
    implementationStatus: 'Planned',
    readinessLevel: 'Architecture Ready',
    tenantConfigurable: true,
    tenantEnablementPotential: 'Multi Tenant Template',
    environmentSupport: { sandbox: true, test: true, production: true },
    awsRelevance: 'Important',
    observabilitySupport: { healthChecks: true, logs: true, metrics: true, alerts: true },
    documentationStatus: 'Vendor Docs Available',
    lastReviewed: '2026-03-19',
    relatedModules: ['Provider Portal', 'Admin Console', 'Billing and Enrollment'],
    tags: ['edifecs', 'claims', 'eligibility', 'administrative-exchange'],
    notes: 'Good fit for organizations using Edifecs as a translation and administrative exchange layer between legacy payer systems and portal-facing APIs.',
    futureAwsMapping: ['API Gateway', 'SQS', 'Step Functions'],
    canonicalModelMapping: ['ClaimSubmission', 'ClaimStatus', 'EligibilityCheck', 'Remittance']
  })
];
