// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/platform/audit" | "/admin/platform/audit-overview" | "/admin/platform/connectivity" | "/admin/platform/connectivity/adapters" | "/admin/platform/connectivity/catalog" | "/admin/platform/connectivity/catalog/[slug]" | "/admin/platform/connectivity/identity" | "/admin/platform/feature-flags" | "/admin/platform/health" | "/admin/platform/metrics" | "/admin/platform/operations/alerts" | "/admin/platform/operations/jobs" | "/admin/platform/operations/logs" | "/admin/platform/reference-data" | "/admin/platform/roles" | "/admin/platform/security/permissions" | "/admin/platform/security/sessions" | "/admin/platform/settings" | "/admin/platform/tenants" | "/admin/platform/tenants/[tenantId]" | "/admin/platform/tenants/configuration" | "/admin/platform/tenants/provisioning" | "/admin/platform/users" | "/admin/tenant/audit" | "/admin/tenant/configuration" | "/admin/tenant/connectivity" | "/admin/tenant/connectivity/sso" | "/admin/tenant/documents" | "/admin/tenant/health" | "/admin/tenant/metrics" | "/admin/tenant/operations/alerts" | "/admin/tenant/operations/jobs" | "/admin/tenant/profile" | "/admin/tenant/roles" | "/admin/tenant/security/access" | "/admin/tenant/users" | "/admin/workspace/[sessionId]" | "/login"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/health" | "/liveness" | "/readiness"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/platform/audit": {}
  "/admin/platform/audit-overview": {}
  "/admin/platform/connectivity": {}
  "/admin/platform/connectivity/adapters": {}
  "/admin/platform/connectivity/catalog": {}
  "/admin/platform/connectivity/catalog/[slug]": { "slug": string; }
  "/admin/platform/connectivity/identity": {}
  "/admin/platform/feature-flags": {}
  "/admin/platform/health": {}
  "/admin/platform/metrics": {}
  "/admin/platform/operations/alerts": {}
  "/admin/platform/operations/jobs": {}
  "/admin/platform/operations/logs": {}
  "/admin/platform/reference-data": {}
  "/admin/platform/roles": {}
  "/admin/platform/security/permissions": {}
  "/admin/platform/security/sessions": {}
  "/admin/platform/settings": {}
  "/admin/platform/tenants": {}
  "/admin/platform/tenants/[tenantId]": { "tenantId": string; }
  "/admin/platform/tenants/configuration": {}
  "/admin/platform/tenants/provisioning": {}
  "/admin/platform/users": {}
  "/admin/tenant/audit": {}
  "/admin/tenant/configuration": {}
  "/admin/tenant/connectivity": {}
  "/admin/tenant/connectivity/sso": {}
  "/admin/tenant/documents": {}
  "/admin/tenant/health": {}
  "/admin/tenant/metrics": {}
  "/admin/tenant/operations/alerts": {}
  "/admin/tenant/operations/jobs": {}
  "/admin/tenant/profile": {}
  "/admin/tenant/roles": {}
  "/admin/tenant/security/access": {}
  "/admin/tenant/users": {}
  "/admin/workspace/[sessionId]": { "sessionId": string; }
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/health": {}
  "/liveness": {}
  "/login": {}
  "/readiness": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
