// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/audit-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/audit-overview">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/audit-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/audit">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/connectivity/adapters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/connectivity/adapters">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/connectivity/adapters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/connectivity/catalog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/connectivity/catalog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/connectivity/catalog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/connectivity/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/connectivity/catalog">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/connectivity/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/connectivity/identity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/connectivity/identity">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/connectivity/identity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/connectivity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/connectivity">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/connectivity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/feature-flags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/feature-flags">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/feature-flags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/health">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/metrics">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/operations/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/operations/alerts">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/operations/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/operations/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/operations/jobs">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/operations/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/operations/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/operations/logs">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/operations/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/reference-data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/reference-data">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/reference-data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/roles">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/security/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/security/permissions">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/security/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/security/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/security/sessions">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/security/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/settings">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/tenants/[tenantId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/tenants/[tenantId]">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/tenants/[tenantId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/tenants/configuration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/tenants/configuration">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/tenants/configuration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/tenants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/tenants">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/tenants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/tenants/provisioning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/tenants/provisioning">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/tenants/provisioning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/platform/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/users">> = Specific
  const handler = {} as typeof import("../../app/admin/platform/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/audit">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/configuration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/configuration">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/configuration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/connectivity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/connectivity">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/connectivity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/connectivity/sso/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/connectivity/sso">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/connectivity/sso/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/documents">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/health">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/metrics">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/operations/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/operations/alerts">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/operations/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/operations/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/operations/jobs">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/operations/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/profile">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/roles">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/security/access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/security/access">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/security/access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tenant/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant/users">> = Specific
  const handler = {} as typeof import("../../app/admin/tenant/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/workspace/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/workspace/[sessionId]">> = Specific
  const handler = {} as typeof import("../../app/admin/workspace/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/health">> = Specific
  const handler = {} as typeof import("../../app/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/liveness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/liveness">> = Specific
  const handler = {} as typeof import("../../app/liveness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/readiness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/readiness">> = Specific
  const handler = {} as typeof import("../../app/readiness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
